CREATE PIPE ${EXAMPLE_DB}.${MAIN_SCHEMA}.my_pipe
  AUTO_INGEST = TRUE
  AS
  COPY INTO ${EXAMPLE_DB}.${MAIN_SCHEMA}.PRODUCTS
  FROM @${EXAMPLE_DB}.${MAIN_SCHEMA}.PRODUCT_DATA_STAGE
  FILE_FORMAT = (TYPE = 'CSV');